"""empty message

Revision ID: 50ab8320bb3f
Revises: 69cd1a38b8ba
Create Date: 2020-02-11 01:06:59.898359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ab8320bb3f'
down_revision = '69cd1a38b8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'quantity')
    # ### end Alembic commands ###
