"""Rename history.removed_dish to history.dishname

Revision ID: 60757a80fc19
Revises: 75ebae8e0d7d
Create Date: 2020-04-02 01:46:15.941460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60757a80fc19'
down_revision = '75ebae8e0d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('dishname', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'history', 'recent_orders', ['recent_order_id'], ['id'])
    op.drop_column('history', 'removed_dish')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('removed_dish', sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_column('history', 'dishname')
    # ### end Alembic commands ###
