"""empty message

Revision ID: 92754d9fc1a5
Revises: 8b693e40f871
Create Date: 2020-03-02 16:22:43.605228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92754d9fc1a5'
down_revision = '8b693e40f871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('total_amount', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'history', 'recent_orders', ['recent_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_column('history', 'total_amount')
    # ### end Alembic commands ###
