"""empty message

Revision ID: 9e04220348e6
Revises: 88c1c77d3209
Create Date: 2020-02-12 23:32:44.372524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e04220348e6'
down_revision = '88c1c77d3209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('quantity', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
